apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-haskell-kubernetes-deployment
  labels:
    app: example-haskell-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-haskell-kubernetes
  template:
    metadata:
      labels:
        app: example-haskell-kubernetes
    spec:
      containers:
      - name: service-a
        image: service-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
      - name: service-b
        image: service-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9001 
---
apiVersion: v1
kind: Service
metadata:
  name: example-haskell-kubernetes-service
spec:
  selector:
    app: example-haskell-kubernetes
  ports:
    - name: example-haskell-kubernetes-service-port
      protocol: TCP
      port: 9003 # within container, behind virtual IP
      targetPort: 9000
      nodePort: 30000
  type: NodePort
